### PR TITLE
DemoProject from UroboSim added

### PR DESCRIPTION
**Pull request by AbhijitVyas**

### CODE REVIEW

**Comment by AbhijitVyas** [comment]
It seems I can not add reviewers to this PR, does anyone know how can I do so? Do I need special rights or be part of the team to create a PR? @Tigul

**Comment by sunava** [comment]
could you please change the name of the folder from demo_project to 'IAI-Kitchen-Robot-Vr-Map' :)? @AbhijitVyas

**Comment by AbhijitVyas** [comment]
> could you please change the name of the folder from demo_project to 'IAI-Kitchen-Robot-Vr-Map' :)? @AbhijitVyas

Done.

**Comment by sunava** [comment]
@AbhijitVyas there is still one file existing Content/Maps/Demo/Demo_IAIKitchen.umap do u need to pus that one too?

**Comment by AbhijitVyas** [comment]
> @AbhijitVyas there is still one file existing Content/Maps/Demo/Demo_IAIKitchen.umap do u need to pus that one too?

No, we do not need it. I have removed it from PR, it still shows the file(but with removed status) It is perhaps because of my original PR was directed toward RobCog:master, but now it should be included into RobCog:dev. Not sure why it still shows, maybe you can accept the PR and see if the Demo folder appears in RobCog:dev?

**Comment by AbhijitVyas** [comment]
> > @AbhijitVyas there is still one file existing Content/Maps/Demo/Demo_IAIKitchen.umap do u need to pus that one too?
> 
> No, we do not need it. I have removed it from PR, it still shows the file(but with removed status) It is perhaps because of my original PR was directed toward RobCog:master, but now it should be included into RobCog:dev. Not sure why it still shows, maybe you can accept the PR and see if the Demo folder appears in RobCog:dev?

I am going to merge this and remove the Demo from RobCog:dev if it appears there.

**Pull request merged**
